name: campus_sense
description: "GeoSense - ubicación y servicios del campus."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0

  provider: ^6.1.5+1

  geolocator: ^14.0.3

  flutter_map: ^8.3.1
  latlong2: ^0.10.1

  camera: ^0.12.0+2

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/