// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdsgUi54z2Qn6Sn2MwOpxnpxSSInrX-r8',
    appId: '1:932517152303:web:792ad07ac46d4f649c28da',
    messagingSenderId: '932517152303',
    projectId: 'campus-sense-raulsalas',
    authDomain: 'campus-sense-raulsalas.firebaseapp.com',
    storageBucket: 'campus-sense-raulsalas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0GxJFUD6Gxc0TF8fHk_nz8xrN4SbWHs',
    appId: '1:932517152303:android:bb7eed98e160209a9c28da',
    messagingSenderId: '932517152303',
    projectId: 'campus-sense-raulsalas',
    storageBucket: 'campus-sense-raulsalas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLEYy2YR46a6phq_VjQdkGfa9y4ntIbG0',
    appId: '1:932517152303:ios:e1debb8d436302bc9c28da',
    messagingSenderId: '932517152303',
    projectId: 'campus-sense-raulsalas',
    storageBucket: 'campus-sense-raulsalas.firebasestorage.app',
    iosBundleId: 'com.example.campusSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLEYy2YR46a6phq_VjQdkGfa9y4ntIbG0',
    appId: '1:932517152303:ios:e1debb8d436302bc9c28da',
    messagingSenderId: '932517152303',
    projectId: 'campus-sense-raulsalas',
    storageBucket: 'campus-sense-raulsalas.firebasestorage.app',
    iosBundleId: 'com.example.campusSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdsgUi54z2Qn6Sn2MwOpxnpxSSInrX-r8',
    appId: '1:932517152303:web:ecd9ed1534991c749c28da',
    messagingSenderId: '932517152303',
    projectId: 'campus-sense-raulsalas',
    authDomain: 'campus-sense-raulsalas.firebaseapp.com',
    storageBucket: 'campus-sense-raulsalas.firebasestorage.app',
  );
}
